import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.*;
import java.io.*;
import java.net.*;
import java.lang.*;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

public class CreateBloodPressure {
	
	// socket for connection to SISServer
	private static Socket universal;
	private static int port = 53217;
	// message writer
	private static MsgEncoder encoder;
	// message reader
	private static MsgDecoder decoder;
	
	// scope of this component
	private static final String SCOPE = "SIS.Scope1";
	// name of this component
	private static final String NAME = "BloodPressure";
	// messages types that can be handled by this component
	private static final List<String> TYPES = new ArrayList<String>(
			Arrays.asList(new String[] { "Setting", "Alert", "Confirm" }));

	// summary for all incoming / outgoing messages
	private static final String incomingMessages = "IN\tConfirm|Setting:Kill|!incomingMessages!";
	private static final String outgoingMessages = "OUT\t Connect|Emergency|Alert";
	
	private static int refreshRate = 500, max = 40, min = 15;
    private static Date startDate = new Date(), endDate = new Date();

    private static Timer timer = new Timer();

	// shared by all kinds of emergencies that can be generated by this component
	private static KeyValueList emergency = new KeyValueList();
	
	//initialCode
	static String alert_msg = "Patient has abnormal bloodPressure ";
	static String doctorEmail = "sisfortest@outlook.com"; // default email
	//static ArrayList<Double> tempRecord = new ArrayList<Double>();

	/*
	 * Main program
	 */
	public static void main(String[] args) {
		while (true) {
			try {
				// try to establish a connection to SISServer
				universal = connect();

				// bind the message reader to inputstream of the socket
				decoder = new MsgDecoder(universal.getInputStream());
				// bind the message writer to outputstream of the socket
				encoder = new MsgEncoder(universal.getOutputStream());

				/*
				 * construct a Connect message to establish the connection
				 */
				KeyValueList conn = new KeyValueList();
				conn.putPair("Scope", SCOPE);
				conn.putPair("MessageType", "Connect");
				conn.putPair("IncomingMessages", incomingMessages);
                conn.putPair("OutgoingMessages", outgoingMessages);
				conn.putPair("Role", "Controller");
				conn.putPair("Name", NAME);
				encoder.sendMsg(conn);

				initRecord();

				// KeyValueList for inward messages, see KeyValueList for
				// details
				KeyValueList kvList;

				while (true) {
					// attempt to read and decode a message, see MsgDecoder for
					// details
					kvList = decoder.getMsg();

					// process that message
					ProcessMsg(kvList);
				}

			} catch (Exception e) {
				// if anything goes wrong, try to re-establish the connection
				try {
					// wait for 1 second to retry
					Thread.sleep(1000);
				} catch (InterruptedException e2) {
				}
				System.out.println("Try to reconnect");
				try {
					universal = connect();
				} catch (IOException e1) {
				}
			}
		}
	}

	/*
	 * used for connect(reconnect) to SISServer
	 */
	static Socket connect() throws IOException {
		Socket socket = new Socket("127.0.0.1", port);
		return socket;
	}
	
	private static void initRecord() {
		emergency.putPair("Scope", SCOPE);
		emergency.putPair("MessageType", "Emergency");
		emergency.putPair("Sender", NAME);
		emergency.putPair("Purpose", "BloodPressureAlert");

		// Receiver may be different for each message, so it doesn't make sense
		// to set here
		emergency.putPair("Receiver", "BloodPressure");
	}
    
    /*private static void componentTask(syst,dias,age,sex){
        if (sex.equals("Male")){
            if (age >= 15 && age <= 18){
            }
            if (age >= 19 && age <= 24){
            }
            if (age >= 25 && age <= 29){
            }
            if (age >= 30 && age <= 35){
            }
            if (age >= 36 && age <= 39){
            }
            if (age >= 40 && age <= 45){
            }
            if (age >= 46 && age <= 49){
            }
            if (age >= 50 && age <= 55){
            }
            if (age >= 56 && age <= 59){
            }
            if (age >= 60){
            }
        }
        else{
            if (age >= 15 && age <= 18){
            }
            if (age >= 19 && age <= 24){
            }
            if (age >= 25 && age <= 29){
            }
            if (age >= 30 && age <= 35){
            }
            if (age >= 36 && age <= 39){
            }
            if (age >= 40 && age <= 45){
            }
            if (age >= 46 && age <= 49){
            }
            if (age >= 50 && age <= 55){
            }
            if (age >= 56 && age <= 59){
            }
            if (age >= 60){
            }
        }
    }*/


	/*
	 * process a certain message, execute corresponding actions
	 */
	static void ProcessMsg(KeyValueList kvList) throws IOException {

		String scope = kvList.getValue("Scope");
		
		String broadcast = kvList.getValue("Broadcast");
		String direction = kvList.getValue("Direction");
		
		if(broadcast!=null&&broadcast.equals("True")){
			
			if(direction!=null&&direction.equals("Up")){
				if(!scope.startsWith(SCOPE)){
					return;
				}
			}else if(direction!=null&&direction.equals("Down")){
				if(!SCOPE.startsWith(scope)){
					return;
				}
			}
		}else{
			if(!SCOPE.equals(scope)){
				return;
			}
		}
		
		String messageType = kvList.getValue("MessageType");
		if(!TYPES.contains(messageType)){
			return;
		}
		
		String sender = kvList.getValue("Sender");
		
		String receiver = kvList.getValue("Receiver");
		
		String purpose = kvList.getValue("Purpose");
		
		switch (messageType) {
		case "Reading":
           System.out.println("BloodPressure received, start processing...");
           String systString = kvList.getValue("Systolic");
           String diasString = kvList.getValue("Diastolic");
           String ageString = kvList.getValue("Age");
           
           String sex = kvList.getValue("SEX");
           int syst = 0, dias = 0, age = 0;
            
           if (systString != null && !systString.equals(""))
           {
               try
               {
                   syst = Integer.parseInt(systString);
               }
               catch(Exception e)
               {
                   syst = 0;
               }
           }
           
           if (diasString != null && !diasString.equals(""))
           {
               try
               {
                   dias = Integer.parseInt(diasString);
               }
               catch(Exception e)
               {
                   dias = 0;
               }
           }
           if (ageString != null && !ageString.equals(""))
           {
               try
               {
                   age = Integer.parseInt(ageString);
               }
               catch(Exception e)
               {
                   age = 0;
               }
           }
           //contains the knowledge base which does the necessary calculations
           //componentTask(syst,dias,age,gender);
		   break;
		case "Confirm":
			System.out.println("Connect to SISServer successful. Boss.");
			break;
		case "Setting":
			if (receiver.equals(NAME)) {
				System.out.println("Message from " + sender);
                System.out.println("Message type: " + messageType);
                System.out.println("Message Purpose: " + purpose);
				switch (purpose) {
					
					case "Activate":
                    String rRate = kvList.getValue("RefreshRate");
                    String sDate = kvList.getValue("StartDate");
                    String eDate = kvList.getValue("EndDate");
                    String maxx = kvList.getValue("Max");
                    String minn = kvList.getValue("Min");

                    if (rRate != null && !rRate.equals(""))
                    {

                        refreshRate = Integer.parseInt(rRate);

                    }

                    if (sDate != null && !sDate.equals("") && eDate != null
                            && !eDate.equals(""))
                    {
                        startDate.setTime(Long.parseLong(sDate));
                        endDate.setTime(Long.parseLong(eDate));
                    }

                    if (maxx != null && !maxx.equals("") && minn != null
                            && !minn.equals(""))
                    {
                        max = Integer.parseInt(maxx);
                        min = Integer.parseInt(minn);
                    }

                   /* try
                    {
                        timer.cancel();
                        timer = new Timer();
                    }
                    catch (Exception e)
                    {
                        // TODO: handle exception
                    }
                    timer.schedule(new TimerTask()
                    {

                        @Override
                        public void run()
                        {
                            // TODO Auto-generated method stub
                            if (System.currentTimeMillis() - endDate.getTime() > 0)
                            {
                                cancel();
                            }
                            else
                            {
                                //componentTask(); 
								System.out.println("Where Component Task is located");
                            }
                        }
                    }, startDate, refreshRate);*/
                    System.out.println("Algorithm Activated");
                    break;

                case "Kill":
                   /* try
                    {
                        timer.cancel();
                    }
                    catch (Exception e)
                    {
                        // TODO: handle exception
                    }*/
                    System.exit(0);
                    break;

                case "Deactivate":
                    try
                    {
                        timer.cancel();
                    }
                    catch (Exception e)
                    {
                        // TODO: handle exception
                    }
                    System.out.println("Algorithm Deactivated");
                    break;
				}
			}
			break;
		}
	}
	}
	

	//!helperCode!


//!helperClassCode!
